#!/usr/bin/env python3
"""
Find verse quotations and dialect passages in the corpus.

Scans base texts for structural markers (<l>, {quote}) and outputs
a TOML-compatible list of refs that contain non-Attic-prose material.

This feeds into greek-check's skip_refs mechanism and supports
the eventual layer annotation (prose / quoted verse / dialect).
"""

import re
from pathlib import Path
from collections import defaultdict


BASE_TEXTS = Path("/Users/jtauber/Development/Greek/vocabulary-corpus-prep/base-texts")


def find_verse_sections(base_texts_dir: Path) -> dict[str, list[dict]]:
    """
    Scan all base texts for verse/dialect indicators.

    Returns: {text_id: [{ref, markers, sample}]}
    """
    results = defaultdict(list)

    for f in sorted(base_texts_dir.rglob("*.base.tsv")):
        text_id = f.stem.replace(".base", "")

        for line in open(f):
            parts = line.strip().split("\t", 1)
            if len(parts) < 2:
                continue
            ref, text = parts

            markers = []

            # Structural verse markers
            if "<l>" in text or "<l " in text:
                markers.append("verse-line")
            if "{quote}" in text:
                markers.append("plato-quote")

            if markers:
                # Extract a clean sample
                clean = re.sub(r"<[^>]+>", " ", text)
                clean = re.sub(r"\{/?quote\}", "", clean)
                clean = re.sub(r"\s+", " ", clean).strip()
                sample = clean[:80]

                results[text_id].append({
                    "ref": ref,
                    "markers": markers,
                    "sample": sample,
                })

    return results


def output_toml_skip_refs(results: dict[str, list[dict]]) -> None:
    """Print skip_refs in TOML format for attic_prose.toml."""
    print("# Verse quotations and dialect passages")
    print("# Auto-generated by find_verse.py")
    print()

    for text_id in sorted(results):
        refs = results[text_id]
        print(f"# {text_id} ({len(refs)} sections)")
        for entry in refs:
            markers = ", ".join(entry["markers"])
            print(f'#   {entry["ref"]} [{markers}]: {entry["sample"][:60]}')
        print()


def output_summary(results: dict[str, list[dict]]) -> None:
    """Print a summary table."""
    total = sum(len(v) for v in results.values())
    print(f"Verse/dialect sections: {total} across {len(results)} texts\n")
    print(f"{'Text':<45} {'Sections':>8}")
    print("-" * 55)
    for text_id in sorted(results):
        print(f"{text_id:<45} {len(results[text_id]):>8}")
    print("-" * 55)
    print(f"{'TOTAL':<45} {total:>8}")


if __name__ == "__main__":
    import sys

    results = find_verse_sections(BASE_TEXTS)

    if "--toml" in sys.argv:
        output_toml_skip_refs(results)
    else:
        output_summary(results)
